=== VadimEisenberg/d2rqUpdateDBUnitTests/doc/example/iswc.dtd
<!ELEMENT dataset (
    conferences*,
    organizations*,
    papers*,
    persons*,
    topics*,
    rel_paper_topic*,
    rel_person_organization*,
    rel_person_paper*,
    rel_person_topic*)>

<!ELEMENT conferences EMPTY>
<!ATTLIST conferences
    ConfID CDATA #REQUIRED
    Name CDATA #IMPLIED
    URI CDATA #IMPLIED
    Date CDATA #IMPLIED
    Location CDATA #IMPLIED
    Datum CDATA #IMPLIED
>

<!ELEMENT organizations EMPTY>
<!ATTLIST organizations
    OrgID CDATA #REQUIRED
    Type CDATA #IMPLIED
    Name CDATA #IMPLIED
    Address CDATA #IMPLIED
    Location CDATA #IMPLIED
    Postcode CDATA #IMPLIED
    Country CDATA #IMPLIED
    URI CDATA #IMPLIED
    Belongsto CDATA #IMPLIED
    Homepage CDATA #IMPLIED
>

<!ELEMENT papers EMPTY>
<!ATTLIST papers
    PaperID CDATA #REQUIRED
    Title CDATA #IMPLIED
    Abstract CDATA #IMPLIED
    URI CDATA #IMPLIED
    Year CDATA #IMPLIED
    Conference CDATA #IMPLIED
    Publish CDATA #IMPLIED
>

<!ELEMENT persons EMPTY>
<!ATTLIST persons
    PerID CDATA #REQUIRED
    Type CDATA #IMPLIED
    FirstName CDATA #IMPLIED
    LastName CDATA #IMPLIED
    Address CDATA #IMPLIED
    Email CDATA #IMPLIED
    Homepage CDATA #IMPLIED
    Phone CDATA #IMPLIED
    URI CDATA #IMPLIED
    Photo CDATA #IMPLIED
>

<!ELEMENT topics EMPTY>
<!ATTLIST topics
    TopicID CDATA #REQUIRED
    TopicName CDATA #IMPLIED
    URI CDATA #IMPLIED
    ParentID CDATA #IMPLIED
>

<!ELEMENT rel_paper_topic EMPTY>
<!ATTLIST rel_paper_topic
    PaperID CDATA #REQUIRED
    TopicID CDATA #REQUIRED
    RelationType CDATA #IMPLIED
>

<!ELEMENT rel_person_organization EMPTY>
<!ATTLIST rel_person_organization
    PersonID CDATA #REQUIRED
    OrganizationID CDATA #REQUIRED
>

<!ELEMENT rel_person_paper EMPTY>
<!ATTLIST rel_person_paper
    PersonID CDATA #REQUIRED
    PaperID CDATA #REQUIRED
>

<!ELEMENT rel_person_topic EMPTY>
<!ATTLIST rel_person_topic
    PersonID CDATA #REQUIRED
    TopicID CDATA #REQUIRED
>

=== VadimEisenberg/d2rqUpdateDBUnitTests/doc/example/iswc.xml
<?xml version='1.0' encoding='UTF-8'?><!DOCTYPE dataset SYSTEM "doc/example/iswc.dtd">
<dataset>
  <conferences ConfID="23541" Name="International Semantic Web Conference 2002" URI="http://annotation.semanticweb.org/iswc/iswc.daml#ISWC_2002" Date="June 9-12, 2002" Location="Sardinia" Datum="2002-10-09 00:00:00.0"/>
  <conferences ConfID="23542" Name="15th International World Wide Web Conference" Date="May 23-26, 2006" Location="Edinburgh" Datum="2006-05-23 00:00:00.0"/>
  <organizations OrgID="1" Name="USC Information Sciences Institute" Address="4676 Admirality Way" Location="Marina Del Rey" Country="United States" URI="http://trellis.semanticweb.org/expect/web/semanticweb/iswc02_trellis.pdf#ISI"/>
  <organizations OrgID="2" Type="U" Name="University of Karlsruhe" URI="http://annotation.semanticweb.org/iswc/iswc.daml#University_of_Karlsruhe"/>
  <organizations OrgID="3" Type="U" Name="International University in Germany" URI="http://www.i-u.de/schools/eberhart/iswc2002/#International University in Germany"/>
  <organizations OrgID="4" Type="I" Name="AIFB" Location="Karlsruhe" Country="Germany" URI="http://annotation.semanticweb.org/iswc/iswc.daml#AIFB" Homepage="http://www.aifb.uni-karlsruhe.de/"/>
  <organizations OrgID="5" Type="D" Name="Department of Computer Science" Address="De Boelelaan 1081a" Location="Amsterdam" Postcode="1081 HV" Country="The Netherlands" URI="http://www.cs.vu.nl/~borys/papers/abstracts/ISWC2002.html#CSVUNL" Belongsto="6"/>
  <organizations OrgID="6" Type="U" Name="Vrije Universiteit Amsterdam" Address="De Boelelaan 1105" Location="Amsterdam" Postcode="1081 HV" Country="The Netherlands" URI="http://www.cs.vu.nl/~borys/papers/abstracts/ISWC2002.html#VrijeUniversiteitAmsterdam"/>
  <organizations OrgID="7" Name="Hewlett-Packard Laboratories, Bristol" Address="Filton Road" Location="Bristol" Postcode="BS34 8QZ" Country="UK" URI="http://www.hpl.hp.co.uk#HPL" Homepage="http://www.hpl.hp.com/"/>
  <organizations OrgID="8" Type="I" Name="Institute for the Protection and Security of the Citizen" Address="Via Enrico Fermi, 1&#xA;21020 - Ispra (Italy)" URI="http://dma.jrc.it#Institute for the Protection and Security of the Citizen"/>
  <organizations OrgID="9" Type="D" Name="Dipartimento di Ingegneria dell&apos;Informazione" Address="Via Vignolese 905" Location="Modena" Country="Italy" URI="http://www.dbgroup.unimo.it/iswc/iswc.html#DII"/>
  <papers PaperID="1" Title="Trusting Information Sources One Citizen at a Time" Abstract="This paper describes an approach to derive assessments about information &#xA;      sources based on individual feedback about the sources. We describe &#xA;      TRELLIS, a system that helps users annotate their analysis of &#xA;      alternative information sources that can be contradictory and &#xA;      incomplete. As the user makes a decision on which sources to dismiss and &#xA;      which to believe in making a final decision, TRELLIS captures the &#xA;      derivation of the decision in a semantic markup. TRELLIS then uses these &#xA;      annotations to derive an assessment of the source based on the &#xA;      annotations of many individuals. Our work builds on the Semantic Web and &#xA;      presents a tool that helps users create annotations that are in a mix of &#xA;      formal and human language, and exploits the formal representations to &#xA;      derive measures of trust in the content of Web resources and their &#xA;      original source." URI="http://trellis.semanticweb.org/expect/web/semanticweb/iswc02_trellis.pdf#Trusting Information Sources One Citizen at a Time" Year="2002" Conference="23541" Publish="true"/>
  <papers PaperID="2" Title="Automatic Generation of Java/SQL based Inference Engines from RDF Schema and RuleML" Abstract="This paper describes two approaches for automatically converting RDF Schema &#xA;and RuleML sources into an inference engine and storage repository. Rather than &#xA;using traditional inference systems, our solution bases on mainstream &#xA;technologies like Java and relational database systems. While this necessarily &#xA;imposes some restrictions, the ease of integration into an existing IT landscape &#xA;is a major advantage. We present the conversion tools and their limitations. &#xA;Furthermore, an extension to RuleML is proposed, that allows Java-enabled &#xA;reaction rules, where calls to Java libraries can be performed upon a rule &#xA;firing. This requires hosts to be Java-enabled when rules and code are moved &#xA;across the web. However, the solution allows for great engineering &#xA;flexibility." URI="http://www.i-u.de/schools/eberhart/iswc2002/#Automatic Generation of Java/SQL based Inference Engines from RDF Schema and RuleML" Year="2002" Conference="23541" Publish="true"/>
  <papers PaperID="3" Publish="true"/>
  <papers PaperID="4" Title="Three Implementations of SquishQL, a Simple RDF Query Language" Abstract="RDF provides a basic way to represent data for the Semantic Web. We have &#xA;      been experimenting with the query paradigm for working with RDF data in &#xA;      semantic web applications. Query of RDF data provides a declarative &#xA;      access mechanism that is suitable for application usage and remote &#xA;      access. We describe work on a conceptual model for querying RDF data &#xA;      that refines ideas first presented in at the W3C workshop on Query &#xA;      Languages and the design of one possible syntax, derived from rdfDB, &#xA;      that is suitable for application programmers. Further, we present &#xA;      experience gained in three implementations of the query language." URI="http://www-uk.hpl.hp.com/people/afs/Abstracts/ISWC2002-SquishQL-Abstract.html#SquishQL" Year="2003" Conference="23541" Publish="true"/>
  <papers PaperID="5" Title="A Data Integration Framework for E-commerce Product Classification" Abstract="A marketplace is &#xA;      the place in which the demand and supply of buyers and vendors &#xA;      participating in a business process may meet. Therefore, electronic &#xA;      marketplaces are virtual communities in which buyers may meet proposals &#xA;      of several suppliers and make the best choice. In the electronic &#xA;      commerce world, the comparison between different products is blocked due &#xA;      to the lack of standards (on the contrary, the proliferation of &#xA;      standards) describing and classifying them. Therefore, the need for B2B &#xA;      and B2C marketplaces is to reclassify products and goods according to &#xA;      different standardization models. This paper aims to face this problem &#xA;      by suggesting the use of a semi-automatic methodology, supported by a &#xA;      tool (SI-Designer), to define the mapping among different e-commerce &#xA;      product classification standards. This methodology was developed for the &#xA;      MOMIS-system within the Intelligent Integration of Information research &#xA;      area. We describe our extension to the methodology that makes it &#xA;      applyable in general to product classification standard, by selecting a &#xA;      fragment of ECCMA/UNSPSC and ecl@ss standard." URI="http://www.dbgroup.unimo.it/iswc/iswc.html#A Data Integration Framework for E-commerce Product Classification" Year="2002" Conference="23541" Publish="true"/>
  <papers PaperID="6" Title="Integrating Vocabularies: Discovering and Representing Vocabulary Maps" Abstract="The Semantic Web would enable new ways of doing business on the&lt;br&gt;Web &#xA;      that require development of advanced business document&lt;br&gt;integration &#xA;      technologies performing intelligent document&lt;br&gt;transformation. The &#xA;      documents use different vocabularies that&lt;br&gt;consist of large &#xA;      hierarchies of terms. Accordingly, vocabulary&lt;br&gt;mapping and &#xA;      transformation becomes an important task in the whole&lt;br&gt;business &#xA;      document transformation process. It includes several&lt;br&gt;subtasks: map &#xA;      discovery, map representation, and map execution&lt;br&gt;that must be &#xA;      seamlessly integrated into the document integration&lt;br&gt;process. In this &#xA;      paper we discuss the process of discovering the&lt;br&gt;maps between two &#xA;      vocabularies assuming availability of two sets of&lt;br&gt;documents, each &#xA;      using one of the vocabularies. We take the&lt;br&gt;vocabularies of product &#xA;      classification codes as a playground and&lt;br&gt;propose a reusable map &#xA;      discovery technique based on Bayesian text&lt;br&gt;classification approach. &#xA;      We show how the discovered maps can be&lt;br&gt;integrated into the document &#xA;      transformation process." URI="http://www.cs.vu.nl/~borys/papers/abstracts/ISWC2002.html#OmelayenkoISWC2002" Year="2003" Conference="23541" Publish="false"/>
